language: java
jdk:
  - openjdk11

branches:
  only:
    - master

cache:
  directories:
    - '$Home/.m2/repository'
    - '$Home/.gradle'

before_install:
  - chmod +x gradlew
script: "./gradlew clean build"

before_deploy:
  - mkdir -p before-deploy
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy *
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/freelec-springboot2-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: springboot-build2
    region: ap-northeast-1
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
    on:
      branch: master

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: springboot-build2
    key: freelec-springboot2-webservice.zip

    bundle_type: zip
    application: springboot2-webservice

    deployment_group: springboot2-webservice-group

    region: ap-northeast-1
    wait-until-deployed: true
    on:
      branch: master

notifications:
  email:
    recipients:
      - wjdac66@gmail.com